### PR TITLE
fix(system_python): Remove printing of not always present attribute

### LINKED ISSUE #3774: Failure in very basic example after upgrading from 1.9 to 2.0 on Debian 10 Buster
# 🐞 bug report

### Affected Rule

py_binary, py_library

### Is this a regression?

Yes, I never saw such issue before 2.0

### Description

Just running a very simple py_binary + py_library, it gives an error

## 🔬 Minimal Reproduction

https://github.com/limdor/bazel-examples/tree/c3f90d396f240aa84555d1337a225bdbe9375e46/python

## 🔥 Exception or Error

```
Traceback (most recent call last):
  File "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/hello_world/generator", line 639, in <module>
    main()
  File "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/hello_world/generator", line 544, in main
    print_verbose("bootstrap sys._base_executable:", sys._base_executable)
AttributeError: module 'sys' has no attribute '_base_executable'
```

## 🌍  Your Environment

**Operating System:**

I've seen the issue on Debian 10 Buster
See https://buildkite.com/bazel/limdor-bazel-examples/builds?branch=renovate%2Frules_python-2.x for environement details where it fails

**Output of `bazel version`:**

8.5.1

**Rules_python version:**

2.0.0 and 2.0.1

**Anything else relevant?**

The error message is like in https://github.com/bazel-contrib/rules_python/issues/3172 but this issue is quite old and not sure if it can be related or not.

### PR DESCRIPTION
**Pull request by limdor**
This attribute is not part of the Python public API and in  Debian 10 Buster (OpenJDK 11, gcc 8.3.0) it seems to not be defined.

This reverts one of the debug logging statements added in https://github.com/bazel-contrib/rules_python/pull/3667

Fixes #3774

### CODE REVIEW

File: python/private/python_bootstrap_template.txt [hunk 1]
```diff
@@ -568,7 +568,6 @@ def main():
   print_verbose("VENV_REL_SITE_PACKAGES:", VENV_REL_SITE_PACKAGES)
   print_verbose("WORKSPACE_NAME:", WORKSPACE_NAME )
   print_verbose("bootstrap sys.executable:", sys.executable)
-  print_verbose("bootstrap sys._base_executable:", sys._base_executable)
```
Comment (aignas) [inline python/private/python_bootstrap_template.txt:571]: Preferably it would be better to not remove but to use `getattr` for this.

```suggestion
  print_verbose("bootstrap sys._base_executable:", getattr(sys, "_base_executable", "unknown"))
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -80,6 +80,8 @@ END_UNRELEASED_TEMPLATE
 * (pypi) Fix `importlib.metadata.files` by ensuring `RECORD` is included in
   installed wheel targets, except when built from sdist
   ([#3024](https://github.com/bazel-contrib/rules_python/issues/3024)).
+* (system_python) Fix AttributeError exception on Debian 10 Buster
```
Comment (aignas) [inline CHANGELOG.md:87]:
```suggestion
* (system_python) Fix AttributeError exception on Debian 10 Buster
  python installations which may not set `sys._base_executable`
```

**Review by aignas — APPROVED** [review]
