### ISSUE TITLE
Failure in very basic example after upgrading from 1.9 to 2.0 on Debian 10 Buster

### ISSUE THREAD

**Issue by limdor** [bazel-contrib/rules_python#3774]
# 🐞 bug report

### Affected Rule

py_binary, py_library

### Is this a regression?

Yes, I never saw such issue before 2.0

### Description

Just running a very simple py_binary + py_library, it gives an error

## 🔬 Minimal Reproduction

https://github.com/limdor/bazel-examples/tree/c3f90d396f240aa84555d1337a225bdbe9375e46/python

## 🔥 Exception or Error

```
Traceback (most recent call last):
  File "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/hello_world/generator", line 639, in <module>
    main()
  File "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/hello_world/generator", line 544, in main
    print_verbose("bootstrap sys._base_executable:", sys._base_executable)
AttributeError: module 'sys' has no attribute '_base_executable'
```

## 🌍  Your Environment

**Operating System:**

I've seen the issue on Debian 10 Buster
See https://buildkite.com/bazel/limdor-bazel-examples/builds?branch=renovate%2Frules_python-2.x for environement details where it fails

**Output of `bazel version`:**

8.5.1

**Rules_python version:**

2.0.0 and 2.0.1

**Anything else relevant?**

The error message is like in https://github.com/bazel-contrib/rules_python/issues/3172 but this issue is quite old and not sure if it can be related or not.

**Comment by aignas** [comment]
It could be failing most likely due to the name of the module that you have. Since in reality very few projects would be named `python`. Please verify if changing the name fixes the behaviour.

**Comment by limdor** [comment]
I'll give it a try and let you know. 

I agree it should not be a common use case the main workspace or the folder containing the main workspace to be called Python. However in a multi language project I could perfectly imagine a subfolder called Python containing Python bindings or Python specific functionality.

**Comment by limdor** [comment]
I just took a quick look and I do not think the problem comes from the root module being called python. In the original builds reported in the ticket I have two examples failing with rules_python 2.0 on Debian, one is pure Python and the main folder is called `python` and the other combines C++ and Python and the main falder is called `cpp_and_python`. I still tried to rename the `cpp_and_python` to `multilanguage`and I'm getting the same error.
https://github.com/limdor/bazel-examples/pull/159
I also deleted the module lock file just in case but that also does not change anything.

**Comment by limdor** [comment]
I just did a bisect and I could identify the cultprit. The problem is this PR
https://github.com/bazel-contrib/rules_python/pull/3667
Looking at the changes it also makes sense, it added the following statement that it was not there before
```
print_verbose("bootstrap sys._base_executable:", sys._base_executable)
```
@rickeylev are you sure that `sys._base_executable` must be always be available? An easy fix would be to only print the variable if it is available.

**Comment by limdor** [comment]
Until it is clear if this variable is expected to be in all supported systems, I would propose to just remove the debug log that was added.
I opened two pull requests, one for main and one for the release/2.0 branch:

- https://github.com/bazel-contrib/rules_python/pull/3781
- https://github.com/bazel-contrib/rules_python/pull/3782

**Comment by limdor** [comment]
I will remove the Windows issue from the ticket. The Windows issue that appeared is another one and I will create another ticket for it.
