### ISSUE TITLE
namespace packages broken because pkgutil shims not generated by default

### ISSUE THREAD

**Issue by philsc** [bazel-contrib/rules_python#3038]
# 🐞 bug report

### Affected Rule

I'm assuming there's some issue in `py_binary` or `py_library`. Not sure.

### Is this a regression?

Yes, 1.4.1 appears to work, but 1.5.0-rc4 does not.

### Description

I can no longer import the `kfp.compiler` module.

## 🔬 Minimal Reproduction

Check out the reproduction here: https://github.com/philsc/rules_python-repro/tree/repro-kfp-1.5.0-rc4

The README showcases the issue I'm running into.

## 🔥 Exception or Error

Doing this:
```python
import kfp
print(kfp)

import kfp.compiler
print(kfp.compiler)
```
And having this BUILD target:
```python
py_binary(
    name = "bin",
    srcs = ["bin.py"],
    deps = [
        requirement("kfp"),
    ],
)
```
results in this error:
```
<module 'kfp' from '/data/phil_cache/bazel/_bazel_philipp.schrader/29d62092ea113224b51636420449a2d3/execroot/__main__/bazel-out/k8-fastbuild/bin/bin.runfiles/my_deps_kfp_pipeline_spec/site-packages/kfp/__init__.py'>
Traceback (most recent call last):
  File "/data/phil_cache/bazel/_bazel_philipp.schrader/29d62092ea113224b51636420449a2d3/execroot/__main__/bazel-out/k8-fastbuild/bin/bin.runfiles/__main__/bin.py", line 4, in <module>
    import kfp.compiler
ModuleNotFoundError: No module named 'kfp.compiler'
```

**Rules_python version:**

`1.5.0`

### Workaround

Set `pip.parse.enable_implicit_namespace_pkgs = True` in 1.5

Note that this will have to be changed to False in subsequent versions; the bug is an inverted logic check after some refactoring.

**Comment by philsc** [comment]
Actually, setting `enable_implicit_namespace_pkgs = True,` fixes the issue in the reproduction that I pushed, but not for our internal repo. I will take a closer look.

**Comment by philsc** [comment]
I think this is an issue in one of our internal packages making some invalid assumptions around imports.

Sorry for the noise!

**Comment by michael-quinlan** [comment]
I'm not sure this is unique to your setup, after upgrading to 1.5 i'm getting

```
ImportError: cannot import name 'genai' from 'google' (/home/shared/.cache/bazel/_bazel_shared/d87484021b443b9cd35511f6aa54a7de/execroot/_main/bazel-out/k8-fastbuild/bin/tool_backend/tool_backend.runfiles/rules_python++pip+pip_311_google_auth/site-packages/google/init.py)
```
which is very similar in that the two google namespaces are not resolving.  1.4.1 worked fine.

enable_implicit_namespace_pkgs = True  seems to fix it on 1.5

**Comment by aaronmaxlevy** [comment]
@philsc would you be willing to re-open this issue?

**Comment by rickeylev** [comment]
fly-by guess: Where and how the pkgutil-style namespace package shims were generated changed from being done in the repo phase to the build phase. https://github.com/bazel-contrib/rules_python/pull/2882

**Comment by rickeylev** [comment]
I poked this a bit

* kfp is a distribution, a wheel
* kfp is a namespace package.
* kfp's wheel is well formed: `kfp/__init__.py` is in the wheel and uses pkgutil-style extend_path()
* kfp-pipeline-spec is a distribution, a wheel
* kfp-pipeline-spec is a well formed. It does not contain `kfp/__init__.py`
* kfp-pipeline-spec adds the kfp.pipeline_spec package to the kfp namespace.

What's happening is `incompatible_default_to_explicit_init_py=false` (default) is mucking things up by creating empty init.py files where there shouldn't be any init.py files. What happens is the empty init.py file turns the package into a regular package, not namespace package, and then the search for other locations doesn't work. Setting enable_implicit_namespace_pkg=True fixes it because it generates an init.py with the pkgutil extend_path code.

But then...why did it ever work in 1.4...?

Ah, I think we accidentally changed the default. In #2882:

```
# python/private/pypi/whl_installer/wheel_installer.py
if not enable_implicit_namespace_pkgs:
    _setup_namespace_pkg_compatibility(installation_dir)

# meanwhile, new logic
# python/private/pypi/whl_library_targets.bzl
if enable_implicit_namespace_pkgs:
    <create pkgutil init shims>
```

Should be a simple fix we can backport and release as 1.5.1

We can also directly test these types of wheels with some new test helpers we have.

**Comment by BryceBeagle** [comment]
I'm still seeing a regression here in behavior. I'm working on upgrading from `rules_python==1.4.1` to `rules_python==1.5.1` and I've bisected the regression to https://github.com/bazel-contrib/rules_python/pull/2882 / dce5120249f62bd04d2bafa48fd053732854e1ad .

The fix in #3059 is not changing any behavior. 

A diff of the sandbox before and after dce5120249f62bd04d2bafa48fd053732854e1ad shows:
```diff
diff --git a/tmp/tree-good.txt b/tmp/tree-bad.txt
index 5e7d588505b4..4aa5a86e7297 100644
--- a/tmp/tree-good.txt
+++ b/tmp/tree-bad.txt
@@ -1,7 +1,5 @@
  site-packages
- ├─ __init__.py → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/__init__.py
  ├─ azure
- │  ├─ __init__.py → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure/__init__.py
  │  └─ identity
  │     ├─ __init__.py → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/__init__.py
  │     ├─ _auth_record.py → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/_auth_record.py
@@ -102,4 +100,4 @@
     ├─ WHEEL → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure_identity-1.16.1.dist-info/WHEEL
     └─ top_level.txt → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure_identity-1.16.1.dist-info/top_level.txt

-8 directories, 94 links
+8 directories, 92 links
```

(the `__init__.py` shims are also missing on the `1.5.1` tag)

**Comment by BryceBeagle** [comment]
Dug a bit deeper. Some (?) of the `__init__.py` files are being generated, but they're being placed at a different path than before:

On `1.4.1`:
```shell
❯ bazel cquery @@pypi_darwin_arm64_azure_identity//:pkg --output=files

external/pypi_darwin_arm64_azure_identity/site-packages/__init__.py
external/pypi_darwin_arm64_azure_identity/site-packages/azure/__init__.py
external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/__init__.py
external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/_auth_record.py
...
external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/aio/_internal/managed_identity_base.py
external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/aio/_internal/managed_identity_client.py
```

On `1.5.1`:
```
❯ bazel cquery @@pypi_darwin_arm64_azure_identity//:pkg --output=files

external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/__init__.py
external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/_auth_record.py
...
external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/aio/_internal/managed_identity_base.py
external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/aio/_internal/managed_identity_client.py
bazel-out/darwin_arm64-fastbuild/bin/external/pypi_darwin_arm64_azure_identity/site-packages/azure/__init__.py
```

Things to note:
- `pypi_darwin_arm64_azure_identity/site-packages/azure/__init__.py` is now in `bazel-out/darwin_arm64-fastbuild/bin/external` instead of `external/`
- `pypi_darwin_arm64_azure_identity/site-packages/__init__.py` no longer exists

**Comment by aignas** [comment]
@BryceBeagle, since the fix fixed @philsc issue, I would love to understand better how the breakage is affecting you.

* The `azure/__init__.py` location should not matter here, because the `runfiles` directory should still be the same.
* The `site-packages/__init__.py` should not matter either, I think, but I am happy to help debug if you see that this affects anything.

**Comment by BryceBeagle** [comment]
Hey @aignas , thanks for the response. The underlying problem is that we're seeing some namespace packages no longer be importable:
```python
  File "/private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/sandbox/darwin-sandbox/1380/execroot/dd_source/domains/assets/libs/dfs/aio/azure.py", line 11, in <module>
    from azure.storage.blob.aio import (
ModuleNotFoundError: No module named 'azure.storage'; 'azure' is not a package
```

In this case, this error is occurring in a directory where there is an `azure.py` file. So Python is trying to import from it instead of the `azure-identity` namespace package.
- In `1.4.1` Python was able to find the `azure-identitiy` namespace package
- If I rename _our_ `azure.py` file to something else, then suddenly Python can _also_ find `azure-identity`
  - This part really confuses me, especially in light of the below information. I'm still not sure how this is working.

I think I've gotten a (bit) better of a grasp to what might be going on, but not fully. I took a look at the difference in runfiles for our target, between `1.4.1` and `1.5.1`. Here, I logged `"\n".join[(rf.path, rf) for rf in runfiles.files.to_list() if "azure" in rf.path]` for both versions and diffed the results:
```diff
❯ diff /tmp/runfiles-1.4.1-azure.txt /tmp/runfiles-1.5.1-azure.txt
13,14d12
< ("external/pypi_darwin_arm64_azure_core/site-packages/__init__.py", <source file site-packages/__init__.py>)
< ("external/pypi_darwin_arm64_azure_core/site-packages/azure/__init__.py", <source file site-packages/azure/__init__.py>)
85,86c83
< ("external/pypi_darwin_arm64_azure_identity/site-packages/__init__.py", <source file site-packages/__init__.py>)
< ("external/pypi_darwin_arm64_azure_identity/site-packages/azure/__init__.py", <source file site-packages/azure/__init__.py>)
---
> ("bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/pypi_darwin_arm64_azure_core/site-packages/azure/__init__.py", <generated file external/pypi_darwin_arm64_azure_core/site-packages/azure/__init__.py>)
173,175c170
< ("external/pypi_darwin_arm64_azure_storage_blob/site-packages/__init__.py", <source file site-packages/__init__.py>)
< ("external/pypi_darwin_arm64_azure_storage_blob/site-packages/azure/__init__.py", <source file site-packages/azure/__init__.py>)
< ("external/pypi_darwin_arm64_azure_storage_blob/site-packages/azure/storage/__init__.py", <source file site-packages/azure/storage/__init__.py>)
---
> ("bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/pypi_darwin_arm64_azure_identity/site-packages/azure/__init__.py", <generated file external/pypi_darwin_arm64_azure_identity/site-packages/azure/__init__.py>)
252a248,249
> ("bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/pypi_darwin_arm64_azure_storage_blob/site-packages/azure/__init__.py", <generated file external/pypi_darwin_arm64_azure_storage_blob/site-packages/azure/__init__.py>)
> ("bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/external/pypi_darwin_arm64_azure_storage_blob/site-packages/azure/storage/__init__.py", <generated file external/pypi_darwin_arm64_azure_storage_blob/site-packages/azure/storage/__init__.py>)
```

The shims are very much so being generated. And they are now under `bazel-out` since they're generated. 

But as you can see in my tree output for the sandbox dir above, these generated files are not being symlinked to in the sandbox.
```diff
diff --git a/tmp/tree-good.txt b/tmp/tree-bad.txt
index 5e7d588505b4..4aa5a86e7297 100644
--- a/tmp/tree-good.txt
+++ b/tmp/tree-bad.txt
@@ -1,7 +1,5 @@
  site-packages
- ├─ __init__.py → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/__init__.py
  ├─ azure
- │  ├─ __init__.py → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure/__init__.py
  │  └─ identity
  │     ├─ __init__.py → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/__init__.py
  │     ├─ _auth_record.py → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure/identity/_auth_record.py
@@ -102,4 +100,4 @@
     ├─ WHEEL → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure_identity-1.16.1.dist-info/WHEEL
     └─ top_level.txt → /private/var/tmp/_bazel_bryce.beagle/e3b0578a6335d5877b9960fc504377a3/execroot/dd_source/external/pypi_darwin_arm64_azure_identity/site-packages/azure_identity-1.16.1.dist-info/top_level.txt

-8 directories, 94 links
+8 directories, 92 links
```

I'm aware of a very similar issue that `rules_rust` deals with. I'm still looking into things, but I wonder if `rules_python` needs to be doing this as well? 

https://github.com/bazelbuild/rules_rust/blob/fbff6e1fe9573efbe05d147f90687461e6e98ed3/rust/private/utils.bzl#L792
```starlark
def transform_sources(ctx, srcs, compile_data, crate_root):
    """Creates symlinks of the source files if needed.

    Rustc assumes that the source files are located next to the crate root.
    In case of a mix between generated and non-generated source files, this
    we violate this assumption, as part of the sources will be located under
    bazel-out/... . In order to allow for targets that contain both generated
    and non-generated source files, we generate symlinks for all non-generated
    files.
    """
    ...
```

Happy to move this to a new/different issue if you think this is unrelated to the above one. Thanks!

**Comment by aignas** [comment]
No this is related, it seems that the existing tests did not cover all of the parts, so there is a bug and we are not creating an `__init__.py` file where we should.

I don't know when I'll have time to look into this, but a patch to it would be welcome. If you search for `namespace` in the `tests` you should be able to find the tests for the code in question, add a regression test and fix the bug (which should be a one line fix).

We can then release this as a 1.5.x release.

**Comment by aignas** [comment]
@BryceBeagle, could you see if #3220 helps?

**Comment by rickeylev** [comment]
This bug is really weird.

Not adding `site-packages/__init__.py` was actually intentional, because it _shouldn't_ matter if it exists or not (it makes `import site-packages` work, but that's not valid). I don't see how the presence or absence of that file would affect anything.

The `site-packages/azure/__init__.py` missing does look like legit bug. I can't see why #3220 would fix it, though. In fact, the existing tests say it _should_ be there.

In order for it to not exist (insofar from python's import perspective), then...it'd have to have external/ on sys.path, maybe?

re: external vs bazel-out, listing of runfiles.path: This is expected and shouldn't matter. The difference is `external/` is referring to a source file (i.e. repo-phase generated`) while bazel-out is referring to a build-time generated file. The distinction disappears once they get merged into the runfiles tree (File.short_path).

We can use whl_from_dir to create a test case for this.

**Comment by aignas** [comment]
Thanks for taking a look once more.

**Comment by rickeylev** [comment]
I pulled down the OP repro last night. The issue is it's using 1.5.0.

fix at main: https://github.com/bazel-contrib/rules_python/commit/47c681b00a8ca75eb34053501f1119d4f6700a4d
backport to 1.5: https://github.com/bazel-contrib/rules_python/commit/18d0d297aa6949f1eb61db963854d5d6918a5a48 (earliest tag shows 1.5.1)

**Comment by BryceBeagle** [comment]
Apologies for the delay in coming back here with a response/update --

It turned out the issue we were seeing above was entirely due to an in-house patch we had made to the `py_binary`/`py_executable` implementation that affected the way runfiles were being collected. Removing this and switching back to upstream implementation fully resolved the issue!

Super sorry for the confusion/noise for something that we had caused on ourselves
