### PR TITLE
deps(gazelle): Bump rules_go from 0.41.0 to 0.55.0

### LINKED ISSUE #2956: chore: update to rules_go v0.55.0
https://github.com/bazel-contrib/rules_go/releases/tag/v0.55.0 was just released. I'm hoping that https://github.com/bazel-contrib/rules_go/pull/4298 included in that release will fix the root issue that caused us to migrate to dougthor42/go-tree-sitter in https://github.com/bazel-contrib/rules_python/pull/2496.

IF this works, then we'll be able to migrate back to smacker/go-tree-sitter and then @jbedard can focus on migrating to the official tree-sitter repos in #2952.

See also:
+ https://github.com/bazel-contrib/rules_python/issues/2630#issuecomment-2923678515 which describes some of the potentially breaking changes in the recent rules_go versions
+ https://github.com/bazel-contrib/bazel-gazelle/issues/2059 which describes the issue in gazelle

### PR DESCRIPTION
**Pull request by dougthor42**
Bump `rules_go` from 0.41.0 to 0.55.0

Fixes #2956.

+ Run `go get github.com/bazelbuild/rules_go@v0.55.0` for version bump.
+ Run `go mod tidy` to clean up stale deps
+ Run `bazel run //:gazelle_update_repos`
+ Figure out http_archive hashes and apply them for WORKSPACE users.
+ Also bump bazel-gazelle to address a warning:
    + `go get github.com/bazelbuild/bazel-gazelle@v0.40.0`
    + > Mismatch between versions requested for module
      > github.com/bazelbuild/bazel-gazelle
      > Bazel dependency version requested in MODULE.bazel: 0.40.0
      > Go module version requested in go.mod: 0.31.1
      > Please resolve this mismatch to prevent discrepancies between
      > native Go and Bazel builds
+ Update CHANGELOG.md accordingly

### CODE REVIEW

**Comment by dougthor42** [comment]
I'm not exactly sure how to fix the failing WORKSPACE tests.

```
(23:42:51) ERROR: no such package '@@org_golang_x_tools//go/vcs': BUILD file not found
in directory 'go/vcs' of external repository @@org_golang_x_tools. Add a BUILD file
to a directory to mark it as a package.
(23:42:51) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d2393494a560f9893c8389cd6840bb63/external/bazel_gazelle/repo/BUILD.bazel:3:11: no
such package '@@org_golang_x_tools//go/vcs': BUILD file not found in directory 'go/vcs'
of external repository @@org_golang_x_tools. Add a BUILD file to a directory to mark it
as a package. and referenced by '@@bazel_gazelle//repo:repo'
```

My assumption is that there's an issue with this go_repository being a nested module, and that `go_repository` is running gazelle on the root `org_golang_x_tools` instead.

```starlark
go_repository(
    name = "org_golang_x_tools_go_vcs",
    importpath = "golang.org/x/tools/go/vcs",
    sum = "h1:cOIJqWBl99H1dH5LWizPa+0ImeeJq3t3cJjaeOWUAL4=",
    version = "v0.1.0-deprecated",
)
```

Any thoughts? I thought that maybe some `build_directives` could help here, but I didn't see any obvious ones. _Maybe_ `gazelle:prefix`?

Thus far I'm unable to reproduce the issue locally, so fixing it might result in some CI spam...

**Comment by dougthor42** [comment]
> Thus far I'm unable to reproduce the issue locally

Reproduced via the very simple `bazel test --noenable_bzlmod --enable_workspace //...` from the gazelle directory :facepalm:.

Investigating a fix.

**Review by aignas — APPROVED** [review]

**Comment by dougthor42** [comment]
@aignas I've solved the WORKSPACE stuff by bumping `gazelle` to 0.40.0, and in doing so had to bump `go` from 1.19.4 to 1.22.0. This go bump looks like it may have broken some BuildKite stuff? `@@bazel_gazelle_is_bazel_module//:defs.bzl`.

Example:

```
(03:46:18) ERROR: error loading package '@@rules_python_gazelle_plugin//': at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_gazelle/def.bzl:16:5: Unable to find package for @@bazel_gazelle_is_bazel_module//:defs.bzl: The repository '@@bazel_gazelle_is_bazel_module' could not be resolved: Repository '@@bazel_gazelle_is_bazel_module' is not defined.
(03:46:18) ERROR: /workdir/BUILD.bazel:36:10: error loading package '@@rules_python_gazelle_plugin//': at /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_gazelle/def.bzl:16:5: Unable to find package for @@bazel_gazelle_is_bazel_module//:defs.bzl: The repository '@@bazel_gazelle_is_bazel_module' could not be resolved: Repository '@@bazel_gazelle_is_bazel_module' is not defined. and referenced by '//:distribution'
```

Can you take a look?

**Comment by dougthor42** [comment]
Huzzah! I got the rest of the Gazelle stuff passing for WORKSPACE.

Now I need to investigate the Windows builds and my tree-sitter fork...

**Comment by dougthor42** [comment]
TL;DR: Might need more updates to `rules_go` before we can move forward. I'll make an Issue there. But not tonight.

---

After much application of my head against a brick wall, I think I've come to the conclusion that https://github.com/bazel-contrib/rules_go/pull/4298 did **not** fully resolve the "not importing C stuff" thing from https://github.com/bazel-contrib/bazel-gazelle/issues/2059.

As you can see from the commit history, I've tried jumping back to smacker/go-tree-sitter, which can't be done because it shares an issue with dougthor42/go-tree-sitter in that things fail on Windows (@shaldengeki saw this in #3060 too).

I've also tried pulling in the official tree-sitter as @jbedard did in #2952. This attempt is why I think that rules_go is still broken, as we get:

```
_main/external/gazelle++go_deps+com_github_tree_sitter_tree_sitter_python/bindings/go/binding.go:4:11: fatal error: ../../src/parser.c: No such file or directory
```

The source file is https://github.com/tree-sitter/tree-sitter-python/blob/master/bindings/go/binding.go and looks like:

```go
package tree_sitter_python

// #cgo CFLAGS: -std=c11 -fPIC
// #include "../../src/parser.c"
// #include "../../src/scanner.c"
import "C"
...
```

Looking at the BUILD.bazel file that gazelle makes for that dependency, we see:

```
$ cat ~/.cache/bazel/_bazel_dthor/518014fa284dfa240d9c6a5ccc9044a0/execroot/_main/external/gazelle++go_deps+com_github_tree_sitter_tree_sitter_python/bindings/go/BUILD.bazel
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go",
    srcs = ["binding.go"],
    cgo = True,
    copts = ["-std=c11 -fPIC"],
    importpath = "github.com/tree-sitter/tree-sitter-python/bindings/go",
    visibility = ["//visibility:public"],
)
...
```

And if we look at the project `tree`, those files _do_ exist... they're just not added as deps to the `go_library` target :sob: 

```
$ tree ~/.cache/bazel/_bazel_dthor/518014fa284dfa240d9c6a5ccc9044a0/execroot/_main/external/gazelle++go_deps+com_github_tree_sitter_tree_sitter_python/                                                                
/usr/local/google/home/dthor/.cache/bazel/_bazel_dthor/518014fa284dfa240d9c6a5ccc9044a0/execroot/_main/external/gazelle++go_deps+com_github_tree_sitter_tree_sitter_python/
├── binding.gyp                
├── bindings              
│   ├── c                   
│   │   ├── tree-sitter-python.h
│   │   └── tree-sitter-python.pc.in
│   ├── go                                           
│   │   ├── binding.go
│   │   ├── binding_test.go   
│   │   └── BUILD.bazel       # hey this is the file I just 'cat'ed
...
├── setup.py
├── src
│   ├── grammar.json
│   ├── node-types.json
│   ├── parser.c              # would you look at that...
│   ├── scanner.c             # there they are!
│   └── tree_sitter
│       ├── alloc.h
│       ├── array.h
│       └── parser.h
├── test
...
└── tree-sitter.json

**Comment by jbedard** [comment]
FWIW I've held back any more effort switching to https://github.com/tree-sitter/go-tree-sitter/ until I get some feedback on https://github.com/tree-sitter/go-tree-sitter/issues/32

**Comment by dougthor42** [comment]
The summary thus far:

+ Tried bumping `rules_go >= 0.55.0` in the hopes that gazelle would be able to make `go_library` target that referenced C files in parent directories, eg [following `#include "../array.h"` in `(smacker|dougthor42)/go-tree-sitter`](https://github.com/smacker/go-tree-sitter/blob/dd81d9e9be82a8cac96ed1d50c7389c5f1997c02/python/scanner.c#L1)
    + Turns out this didn't work. Or perhaps more accurately, I misunderstood what https://github.com/bazel-contrib/rules_go/pull/4298 was supposed to fix.
    + `rules_go >= 0.55.0` requires `go >= v1.22`
+ We can't bump go above v1.19 because `(smacker|dougthor42)/go-tree-sitter` fails to build on Windows with an error `...go_tree_sitter\iter.go:17:18: undefined: Node`.
+ While I have access to a Windows host, I do not know enough `go` to be able to update dougthor42/go-tree-sitter to work with `go >= 1.22`.
    + And I don't have access while at work, so my time is very limited.
+ Tried using `http_archive` to pull in the official tree-sitter and manually inject our own BUILD files instead of having Gazelle autogenerate them
    + This was too complex of a task, but did get me to think of the next item
+ Tried using `http_archive` to pull the `smacker/go-tree-sitter` and manually inject our own BUILD files instead of having Gazelle autogenerate them
    + So far so good...

**Comment by dougthor42** [comment]
Replaced by #3179.

Good riddance to this PR, because it was super annoying for some reason.
