### PR TITLE
fix(system_python): backport Debian 10 Buster bug into 2.0.2

### LINKED ISSUE #3774: Failure in very basic example after upgrading from 1.9 to 2.0 on Debian 10 Buster
# 🐞 bug report

### Affected Rule

py_binary, py_library

### Is this a regression?

Yes, I never saw such issue before 2.0

### Description

Just running a very simple py_binary + py_library, it gives an error

## 🔬 Minimal Reproduction

https://github.com/limdor/bazel-examples/tree/c3f90d396f240aa84555d1337a225bdbe9375e46/python

## 🔥 Exception or Error

```
Traceback (most recent call last):
  File "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/hello_world/generator", line 639, in <module>
    main()
  File "bazel-out/k8-opt-exec-ST-d57f47055a04/bin/hello_world/generator", line 544, in main
    print_verbose("bootstrap sys._base_executable:", sys._base_executable)
AttributeError: module 'sys' has no attribute '_base_executable'
```

## 🌍  Your Environment

**Operating System:**

I've seen the issue on Debian 10 Buster
See https://buildkite.com/bazel/limdor-bazel-examples/builds?branch=renovate%2Frules_python-2.x for environement details where it fails

**Output of `bazel version`:**

8.5.1

**Rules_python version:**

2.0.0 and 2.0.1

**Anything else relevant?**

The error message is like in https://github.com/bazel-contrib/rules_python/issues/3172 but this issue is quite old and not sure if it can be related or not.

### PR DESCRIPTION
**Pull request by limdor**
This attribute is not part of the Python public API and in  Debian 10 Buster (OpenJDK 11, gcc 8.3.0) it seems to not be defined.

This reverts one of the debug logging statements added in https://github.com/bazel-contrib/rules_python/pull/3667

Fixes #3774

### CODE REVIEW

**Comment by limdor** [comment]
@aignas what would you like me to do with this PR? Is the merge in master enough to the in the next minor version? I do not care from my side on a patch version.

**Comment by aignas** [comment]
If you don't care for the patch version, then we can close this, this will be released with 2.1.0
